import Foundation

// Дополнительные английские колоды: IT/SRE, Business, Immigration, Travel, Idioms, Phrasal Advanced.
// Используются в FolderOrganizer для наполнения английских подпапок.

struct EnglishExtraDecks {
    typealias Entry = (front: String, back: String, example: String)

    // MARK: - IT / SRE / DevOps (~80)
    static let itSre: [Entry] = [
        ("deploy", "деплоить, развёртывать", "We deploy to production on Fridays (not recommended)."),
        ("deployment", "развёртывание", "The deployment took 15 minutes."),
        ("rollback", "откат, откатить", "Rollback the release if metrics drop."),
        ("rollout", "раскатка, поэтапное развёртывание", "Gradual rollout reduces blast radius."),
        ("canary release", "канареечный релиз", "We saw errors on the canary before full rollout."),
        ("blue-green deployment", "сине-зелёный деплой", "Blue-green deploy lets us switch traffic instantly."),
        ("zero-downtime", "без простоя", "We achieved zero-downtime migration."),
        ("downtime", "простой, даунтайм", "Yesterday's downtime cost us hours."),
        ("uptime", "аптайм, непрерывная работа", "Four nines of uptime is the SLA target."),
        ("SLA", "соглашение об уровне обслуживания", "Breaching the SLA triggers credits."),
        ("SLO", "цель уровня сервиса", "Our latency SLO is 200ms p95."),
        ("SLI", "индикатор уровня сервиса", "The SLI is the actual measurement."),
        ("error budget", "бюджет ошибок", "We burned half our error budget this quarter."),
        ("postmortem", "посмертный разбор, post-mortem", "Write a blameless postmortem after the outage."),
        ("blameless", "без поиска виноватых", "We do blameless reviews to encourage honesty."),
        ("root cause", "корневая причина", "The root cause was a misconfigured timeout."),
        ("root cause analysis", "анализ первопричин", "RCA uncovered three contributing factors."),
        ("outage", "авария, перебой", "The outage lasted 40 minutes."),
        ("incident", "инцидент", "P1 incidents page the on-call engineer."),
        ("on-call", "дежурство", "I'm on-call this week."),
        ("paging", "вызов пейджером, алерт", "The high-CPU alert is paging me now."),
        ("alert", "оповещение, алерт", "We tuned alerts to reduce noise."),
        ("alert fatigue", "усталость от алертов", "Too many alerts cause fatigue and ignored pages."),
        ("false positive", "ложное срабатывание", "This alert has been a false positive all week."),
        ("latency", "задержка (в миллисекундах)", "Tail latency matters more than average."),
        ("throughput", "пропускная способность", "Throughput peaked at 10k RPS."),
        ("bottleneck", "узкое место", "The DB is the bottleneck, not the app."),
        ("scale up", "масштабировать вверх (мощнее)", "We scaled up the instance type."),
        ("scale out", "масштабировать горизонтально", "Scale out by adding more replicas."),
        ("autoscaling", "автомасштабирование", "Autoscaling kicked in during the traffic spike."),
        ("load balancer", "балансировщик нагрузки", "The load balancer health-checks each pod."),
        ("reverse proxy", "обратный прокси", "NGINX sits as a reverse proxy."),
        ("CI/CD", "непрерывная интеграция/доставка", "The CI/CD pipeline runs tests on every commit."),
        ("pipeline", "пайплайн, конвейер сборки", "Jenkins pipeline is in a Jenkinsfile."),
        ("build", "сборка", "The build failed at the integration tests."),
        ("artifact", "артефакт (результат сборки)", "Upload artifacts to Artifactory."),
        ("registry", "реестр образов", "Push the image to the Docker registry."),
        ("image", "образ (докера)", "The image is 500 MB — too large."),
        ("container", "контейнер", "Kill the stuck container."),
        ("orchestration", "оркестрация", "Kubernetes handles container orchestration."),
        ("cluster", "кластер", "The cluster runs 200 nodes."),
        ("node", "узел", "Node cordoned — ready to drain."),
        ("pod", "под (в K8s)", "The pod keeps crash-looping."),
        ("crash loop", "бесконечный перезапуск", "CrashLoopBackOff means the container keeps failing."),
        ("namespace", "пространство имён", "Each team has its own namespace."),
        ("sidecar", "sidecar-контейнер", "The sidecar handles logging."),
        ("manifest", "манифест (YAML)", "Apply the manifest with kubectl."),
        ("chart", "чарт (Helm)", "Helm charts bundle K8s resources."),
        ("rolling update", "скользящее обновление", "Rolling update replaces pods gradually."),
        ("health check", "проверка работоспособности", "Readiness probe gates traffic."),
        ("readiness probe", "проба готовности", "Readiness returns 200 when pod can serve."),
        ("liveness probe", "проба живости", "Liveness kicks when app is deadlocked."),
        ("graceful shutdown", "корректное завершение", "Graceful shutdown drains in-flight requests."),
        ("signal", "сигнал (SIGTERM и т.п.)", "Kubernetes sends SIGTERM before SIGKILL."),
        ("backpressure", "обратное давление", "Add backpressure to avoid overloading downstream."),
        ("circuit breaker", "автоматический выключатель", "Circuit breaker stops cascading failures."),
        ("retry", "повтор запроса", "Retry with exponential backoff."),
        ("exponential backoff", "экспоненциальное ожидание", "Exponential backoff prevents thundering herd."),
        ("timeout", "таймаут", "Set a sane timeout on every network call."),
        ("idempotent", "идемпотентный", "Make retries safe — operations must be idempotent."),
        ("throttling", "ограничение частоты", "We throttle heavy users to protect the service."),
        ("rate limit", "лимит запросов", "Rate-limited: 100 req/min per key."),
        ("debounce", "дебаунс, сглаживание", "Debounce the save on user input."),
        ("observability", "наблюдаемость", "Observability = logs + metrics + traces."),
        ("instrumentation", "инструментирование", "Add instrumentation to critical paths."),
        ("tracing", "трейсинг (распределённый)", "Distributed tracing follows a request across services."),
        ("log aggregation", "агрегация логов", "We ship logs to Loki for aggregation."),
        ("dashboard", "дашборд, панель", "Pin the Grafana dashboard to the wall."),
        ("metric", "метрика", "Track this metric as an SLI."),
        ("gauge", "gauge (тип метрики)", "CPU usage is a gauge."),
        ("counter", "counter (тип метрики)", "Request count is a counter."),
        ("histogram", "гистограмма", "Latency histogram shows the distribution."),
        ("heatmap", "тепловая карта", "Heatmap reveals hidden latency patterns."),
        ("anomaly", "аномалия", "The alert triggers on anomalies."),
        ("capacity planning", "планирование мощностей", "Capacity planning avoids surprise outages."),
        ("load test", "нагрузочное тестирование", "Run a load test before Black Friday."),
        ("chaos engineering", "chaos engineering, учения", "Chaos engineering tests resilience."),
        ("failover", "отказоустойчивый переключатель", "Failover to the secondary region."),
        ("secondary region", "резервный регион", "We replicate to a secondary region."),
        ("replica", "реплика", "Three read replicas handle the load."),
        ("sharding", "шардирование", "Shard the DB by user ID."),
        ("quorum", "кворум", "Writes need majority quorum."),
        ("eventual consistency", "итоговая согласованность", "Eventual consistency simplifies distributed writes."),
        ("secret", "секрет, учётные данные", "Rotate the secret every 90 days."),
        ("vault", "vault, хранилище секретов", "Fetch the password from Vault."),
        ("entitlement", "право, разрешение", "Grant minimum entitlements — principle of least privilege."),
        ("principle of least privilege", "принцип минимальных привилегий", "Follow least privilege when granting IAM roles."),
        ("ephemeral", "эфемерный, временный", "Build agents are ephemeral."),
        ("immutable infrastructure", "неизменяемая инфраструктура", "Immutable infra — replace, don't mutate."),
        ("infrastructure as code", "инфраструктура как код (IaC)", "Terraform is our IaC tool."),
        ("drift", "расхождение (с манифестом)", "Terraform plan shows configuration drift.")
    ]

    // MARK: - Business English (~70)
    static let business: [Entry] = [
        ("let me know", "дайте знать, сообщите", "Let me know if you need anything."),
        ("ping me", "напиши мне (в чат)", "Ping me when the build is green."),
        ("loop in", "подключить к обсуждению", "I'll loop in the security team."),
        ("circle back", "вернуться к вопросу позже", "Let's circle back next week."),
        ("touch base", "связаться, обсудить", "Let's touch base on Friday."),
        ("follow up", "уточнить, вернуться позже", "I'll follow up with the client tomorrow."),
        ("reach out", "написать, связаться", "Reach out if you have questions."),
        ("get back to you", "вернусь к вам с ответом", "I'll get back to you by EOD."),
        ("EOD", "конец рабочего дня (end of day)", "Send the report by EOD."),
        ("EOW", "конец недели (end of week)", "Aiming for EOW delivery."),
        ("ETA", "ожидаемое время (estimated time of arrival)", "What's the ETA on the fix?"),
        ("blocker", "блокер, препятствие", "Is this a blocker for the release?"),
        ("FYI", "для информации (for your information)", "FYI, the deploy is scheduled for 6pm."),
        ("ASAP", "как можно скорее", "I need this ASAP, please."),
        ("TBD", "будет определено позже (to be determined)", "Timeline: TBD."),
        ("TBC", "будет подтверждено (to be confirmed)", "Dates TBC."),
        ("OOO", "вне офиса (out of office)", "I'll be OOO next week."),
        ("PTO", "отпуск (paid time off)", "Taking PTO on Monday."),
        ("sign off", "согласовать, одобрить", "The VP needs to sign off on the budget."),
        ("kick off", "запустить, начать (проект)", "We kick off the project Monday."),
        ("wrap up", "завершить, закруглить", "Let's wrap up this discussion."),
        ("push back", "отложить, сопротивляться", "We pushed back the deadline by a week."),
        ("buy-in", "поддержка, согласие", "We need executive buy-in first."),
        ("stakeholder", "заинтересованная сторона", "Align with all key stakeholders."),
        ("deliverable", "результат, артефакт (работы)", "The main deliverable is the report."),
        ("take ownership", "взять ответственность", "Who's taking ownership of this ticket?"),
        ("own it", "отвечать за это", "I own the backend piece."),
        ("heads up", "предупреждение, уведомление", "Heads up — the API is changing."),
        ("a heads-up", "предупреждение (сущ.)", "Thanks for the heads-up."),
        ("on the same page", "на одной волне", "Let's make sure we're on the same page."),
        ("align", "согласовать подходы", "Can we align on the approach first?"),
        ("sync", "синхронизироваться (встреча)", "Let's have a quick sync."),
        ("quick sync", "короткая сверка", "15-min quick sync tomorrow?"),
        ("standup", "ежедневная летучка", "Standup is at 10."),
        ("retro", "ретроспектива", "Sprint retro is on Friday."),
        ("action item", "задача, пункт действий", "Capture action items in the doc."),
        ("takeaway", "вывод, главная мысль", "My main takeaway: we need more testing."),
        ("low-hanging fruit", "лёгкая добыча, простая победа", "Let's go after the low-hanging fruit first."),
        ("move the needle", "дать заметный эффект", "This change actually moves the needle."),
        ("bandwidth", "время, ресурсы (свободные)", "I don't have bandwidth this sprint."),
        ("capacity", "пропускная способность команды", "Team capacity is down two engineers."),
        ("scope", "объём работ", "Scope creep is killing the timeline."),
        ("scope creep", "разрастание задачи", "Beware of scope creep."),
        ("out of scope", "за рамками задачи", "That's out of scope for this release."),
        ("MVP", "минимальный жизнеспособный продукт", "Ship the MVP, then iterate."),
        ("iterate", "итерировать, дорабатывать", "We'll iterate based on feedback."),
        ("North Star", "главная цель, ориентир", "Revenue is the North Star metric."),
        ("KPI", "ключевой показатель эффективности", "KPIs are reviewed quarterly."),
        ("quarterly", "ежеквартально", "We plan quarterly."),
        ("roadmap", "дорожная карта", "The roadmap is public internally."),
        ("backlog", "бэклог, очередь задач", "The backlog is overflowing."),
        ("triage", "разбор, сортировка", "Triage the incoming tickets Monday morning."),
        ("bandwidth-limited", "ограничен по времени", "I'm bandwidth-limited this week."),
        ("bottom line", "суть, итог", "Bottom line: we ship or we cut features."),
        ("game plan", "план действий", "What's the game plan for next quarter?"),
        ("moving forward", "в дальнейшем", "Moving forward, let's document this."),
        ("going forward", "впредь", "Going forward, we'll rotate on-call."),
        ("in the weeds", "глубоко в деталях", "Don't get too in the weeds here."),
        ("dive in", "погрузиться, начать изучать", "Let me dive in and investigate."),
        ("deep dive", "глубокое погружение", "Schedule a deep dive on the architecture."),
        ("walk through", "провести по шагам", "Walk me through your change."),
        ("ramp up", "разогнаться, войти в тему", "New hires need time to ramp up."),
        ("onboarding", "адаптация новичков", "Onboarding takes two weeks."),
        ("offboarding", "передача дел при уходе", "Offboarding checklist is in the wiki."),
        ("1:1", "личная встреча с менеджером", "1:1 with my manager is on Tuesdays."),
        ("career growth", "карьерный рост", "Let's discuss career growth in our next 1:1."),
        ("promotion", "повышение", "He was up for promotion to staff."),
        ("perf review", "оценка эффективности", "Perf reviews happen twice a year."),
        ("raise", "прибавка к зарплате", "I got a small raise this year."),
        ("compensation", "компенсация, зарплата", "Compensation includes base plus equity."),
        ("equity", "опционы, акции компании", "Equity vests over four years.")
    ]

    // MARK: - Immigration / Visa (~55)
    static let immigration: [Entry] = [
        ("residence permit", "вид на жительство (ВНЖ)", "My residence permit expires in 2028."),
        ("permanent residence", "ПМЖ", "Permanent residence after 5 years."),
        ("citizenship", "гражданство", "Argentine citizenship takes 2 years."),
        ("naturalization", "натурализация", "Naturalization requires a language test."),
        ("applicant", "заявитель", "The applicant must submit form I-485."),
        ("application", "заявление, анкета", "Submit your application by the deadline."),
        ("sponsor", "спонсор, поручитель", "My employer is my visa sponsor."),
        ("sponsorship", "спонсорство, поручительство", "Sponsorship is valid for 3 years."),
        ("petition", "ходатайство, петиция", "File the I-140 petition."),
        ("approval", "одобрение", "We're awaiting approval."),
        ("rejection", "отказ", "The rejection letter listed specific reasons."),
        ("denial", "отказ (в визе)", "Visa denial can be appealed."),
        ("appeal", "апелляция", "We filed an appeal within 30 days."),
        ("consulate", "консульство", "Visit the consulate for the interview."),
        ("embassy", "посольство", "The embassy issues visas."),
        ("visa", "виза", "Work visa requires a job offer."),
        ("work visa", "рабочая виза", "HSP is a highly skilled work visa."),
        ("student visa", "студенческая виза", "Student visa limits work hours."),
        ("tourist visa", "туристическая виза", "Tourist visa is usually 90 days."),
        ("transit visa", "транзитная виза", "Transit visa for airport layover."),
        ("biometrics", "биометрия", "Biometrics appointment takes 20 minutes."),
        ("fingerprints", "отпечатки пальцев", "Fingerprints are taken at biometrics."),
        ("photograph", "фотография (в анкете)", "Bring a passport photograph."),
        ("issue", "выдавать (документ)", "The visa was issued yesterday."),
        ("issuance", "выдача", "Visa issuance can take weeks."),
        ("expire", "истекать (о сроке)", "My permit expires next month."),
        ("expiration date", "дата истечения", "Check the expiration date on your visa."),
        ("extend", "продлить", "You can extend your visa once."),
        ("extension", "продление", "File the extension 60 days in advance."),
        ("renewal", "возобновление, перевыпуск", "Renewal requires a new medical check."),
        ("deadline", "дедлайн", "Miss the deadline and start over."),
        ("documentation", "документация", "Gather all supporting documentation."),
        ("supporting documents", "подтверждающие документы", "Include supporting documents with your application."),
        ("proof of income", "подтверждение доходов", "Proof of income: last 3 payslips."),
        ("payslip", "расчётный листок", "Payslips must be stamped."),
        ("bank statement", "банковская выписка", "Six months of bank statements."),
        ("tax return", "налоговая декларация", "Attach your latest tax return."),
        ("diploma", "диплом", "Notarized diploma with apostille."),
        ("apostille", "апостиль", "Get an apostille on your birth certificate."),
        ("notarize", "заверить нотариально", "Notarize the translation."),
        ("notary", "нотариус", "Find a notary public."),
        ("translation", "перевод (документа)", "Certified translation required."),
        ("certified translation", "сертифицированный перевод", "Submit certified translations."),
        ("criminal record", "справка о несудимости", "Police clearance — criminal record check."),
        ("police clearance", "справка из полиции", "Police clearance from every country you lived in."),
        ("medical check", "медицинское обследование", "Medical check at an approved clinic."),
        ("health insurance", "медицинская страховка", "Mandatory health insurance coverage."),
        ("dependent", "иждивенец", "Spouse and children are dependents."),
        ("spouse", "супруг/супруга", "Spouse visa is a derivative status."),
        ("derivative status", "производный статус", "Children get derivative status."),
        ("quota", "квота", "Work visa quota resets in April."),
        ("cap", "потолок (квоты)", "The cap is 85,000 per year."),
        ("lottery", "лотерея (для виз H-1B)", "H-1B lottery odds are 30%."),
        ("port of entry", "пункт въезда", "Officer at the port of entry stamped my passport."),
        ("stamp", "штамп", "The stamp shows your authorized stay."),
        ("overstay", "превысить срок пребывания", "Overstay triggers a ban.")
    ]

    // MARK: - Travel: Airport & Transport (~30)
    static let travelAirport: [Entry] = [
        ("boarding pass", "посадочный талон", "Show your boarding pass at the gate."),
        ("check-in", "регистрация на рейс", "Check-in closes 40 minutes before departure."),
        ("check-in counter", "стойка регистрации", "Check-in counter is on the second floor."),
        ("boarding", "посадка", "Boarding starts at 6:30."),
        ("departure", "вылет", "Departure is from gate 23."),
        ("arrival", "прилёт", "Arrival was delayed by an hour."),
        ("layover", "пересадка, стыковка", "A 2-hour layover in Frankfurt."),
        ("connecting flight", "стыковочный рейс", "Connecting flight to Tokyo."),
        ("direct flight", "прямой рейс", "Is there a direct flight?"),
        ("round trip", "туда-обратно", "I booked a round-trip ticket."),
        ("one-way", "в одну сторону", "One-way tickets are often cheaper."),
        ("delayed", "задержан", "The flight is delayed again."),
        ("cancelled", "отменён", "My flight was cancelled due to weather."),
        ("on time", "по расписанию", "The plane arrived on time."),
        ("gate", "выход на посадку", "Which gate is flight 307 from?"),
        ("terminal", "терминал", "International flights leave from Terminal 2."),
        ("customs", "таможня", "Anything to declare at customs?"),
        ("declare", "задекларировать", "You must declare cash over $10,000."),
        ("immigration", "паспортный контроль", "Long line at immigration today."),
        ("passport control", "паспортный контроль", "Passport control took 40 minutes."),
        ("baggage claim", "выдача багажа", "Baggage claim is downstairs."),
        ("carry-on", "ручная кладь", "Carry-on must fit in the bin."),
        ("checked bag", "регистрируемый багаж", "Two checked bags included."),
        ("overweight", "с перевесом", "Your bag is overweight — $100 fee."),
        ("fragile", "хрупкий", "Put a fragile tag on the violin case."),
        ("lost luggage", "потерянный багаж", "File a lost luggage report here."),
        ("duty-free", "беспошлинный", "Duty-free after security."),
        ("jet lag", "джетлаг", "I'm fighting serious jet lag."),
        ("aisle seat", "место у прохода", "I prefer an aisle seat."),
        ("window seat", "место у окна", "Window seat, please.")
    ]

    // MARK: - Travel: Hotel & Restaurant (~30)
    static let travelHotelFood: [Entry] = [
        ("reservation", "бронь", "I have a reservation under Maks."),
        ("book", "забронировать", "I booked a room for two nights."),
        ("availability", "наличие мест", "Is there any availability for Friday?"),
        ("vacancy", "свободные номера", "Sorry, no vacancy tonight."),
        ("check in", "заселиться", "Check in starts at 3pm."),
        ("check out", "выписаться", "Check out by 11am."),
        ("late check-out", "поздний выезд", "Can I get a late check-out?"),
        ("front desk", "ресепшн", "Leave your key at the front desk."),
        ("concierge", "консьерж", "The concierge can recommend restaurants."),
        ("single room", "одноместный номер", "A single room, please."),
        ("double room", "двухместный номер", "We'd like a double room with a king bed."),
        ("suite", "люкс, сьют", "Can we upgrade to a suite?"),
        ("amenities", "удобства", "The hotel amenities include a pool."),
        ("breakfast included", "с завтраком", "Is breakfast included?"),
        ("room service", "обслуживание в номер", "I'll order room service."),
        ("housekeeping", "уборка в номере", "Housekeeping comes daily."),
        ("deposit", "депозит, залог", "A $100 deposit is required at check-in."),
        ("menu", "меню", "Can I see the menu?"),
        ("appetizer", "закуска", "We'll start with two appetizers."),
        ("main course", "основное блюдо", "What's the main course today?"),
        ("dessert", "десерт", "Dessert menu, please."),
        ("bill / check", "счёт", "Could we get the check, please?"),
        ("tip", "чаевые", "Tip is included in Europe."),
        ("split the bill", "разделить счёт", "Can we split the bill?"),
        ("takeaway / to-go", "еда на вынос / с собой", "I'll have it to go."),
        ("refill", "долить, дозаправить (напиток)", "Free refills on coffee."),
        ("well done", "хорошо прожаренный", "Steak well done, please."),
        ("medium rare", "средней прожарки", "I'll have the burger medium rare."),
        ("allergy", "аллергия", "I have a nut allergy."),
        ("vegetarian", "вегетарианец", "Do you have vegetarian options?")
    ]

    // MARK: - Travel: Directions & City (~25)
    static let travelDirections: [Entry] = [
        ("go straight", "идите прямо", "Go straight for two blocks."),
        ("turn left", "поверните налево", "Turn left at the traffic light."),
        ("turn right", "поверните направо", "Turn right at the corner."),
        ("block", "квартал", "It's three blocks away."),
        ("intersection", "перекрёсток", "Cross at the intersection."),
        ("traffic light", "светофор", "Wait at the traffic light."),
        ("crosswalk", "пешеходный переход", "Use the crosswalk."),
        ("sidewalk", "тротуар", "Walk on the sidewalk."),
        ("nearby", "рядом", "Is there an ATM nearby?"),
        ("around the corner", "за углом", "The café is around the corner."),
        ("across from", "напротив", "The hotel is across from the station."),
        ("next to", "рядом с", "It's next to the bank."),
        ("landmark", "ориентир", "The clock tower is a famous landmark."),
        ("subway", "метро", "The subway runs until midnight."),
        ("bus stop", "остановка автобуса", "The nearest bus stop is two minutes away."),
        ("train station", "вокзал", "Central train station is huge."),
        ("platform", "платформа", "Track 5, platform B."),
        ("one-way ticket", "билет в одну сторону", "One-way ticket to Kyoto."),
        ("timetable", "расписание", "Check the timetable on the app."),
        ("rush hour", "час пик", "Avoid the subway during rush hour."),
        ("fare", "стоимость проезда", "The fare is 500 yen."),
        ("map", "карта", "Can I see a map?"),
        ("detour", "объезд", "There's a detour due to construction."),
        ("shortcut", "короткий путь", "I know a shortcut."),
        ("get lost", "заблудиться", "I always get lost in this city.")
    ]

    // MARK: - Idioms (~70)
    static let idioms: [Entry] = [
        ("hit the sack", "пойти спать, залечь", "I'm exhausted — gonna hit the sack."),
        ("break the ice", "растопить лёд", "He told a joke to break the ice."),
        ("piece of cake", "проще простого", "The test was a piece of cake."),
        ("under the weather", "не в форме, приболеть", "I'm feeling under the weather today."),
        ("cost an arm and a leg", "стоить целое состояние", "That car cost an arm and a leg."),
        ("the ball is in your court", "теперь ход за тобой", "I sent the offer — the ball's in your court."),
        ("bite the bullet", "стиснуть зубы", "Just bite the bullet and do it."),
        ("burn the midnight oil", "работать допоздна", "She's burning the midnight oil on the proposal."),
        ("call it a day", "закруглиться", "Let's call it a day."),
        ("cut corners", "халтурить, срезать путь", "Don't cut corners on security."),
        ("get the hang of it", "приноровиться", "I'm getting the hang of Vim."),
        ("go the extra mile", "приложить доп. усилия", "He always goes the extra mile."),
        ("hit the nail on the head", "попасть в точку", "You hit the nail on the head."),
        ("in hot water", "в беде, в трудном положении", "He's in hot water with the boss."),
        ("jump on the bandwagon", "присоединиться к модному", "Everyone's jumping on the AI bandwagon."),
        ("keep an eye on", "присматривать", "Keep an eye on the metrics."),
        ("let the cat out of the bag", "выболтать секрет", "Don't let the cat out of the bag."),
        ("miss the boat", "упустить шанс", "You missed the boat on that deal."),
        ("on the fence", "колеблюсь, не решил", "I'm on the fence about the job offer."),
        ("pull someone's leg", "подшучивать над кем-то", "Relax, I'm just pulling your leg."),
        ("rain on someone's parade", "портить праздник", "I hate to rain on your parade, but…"),
        ("see eye to eye", "сходиться во взглядах", "We don't see eye to eye on this."),
        ("spill the beans", "разболтать", "Come on, spill the beans!"),
        ("take it with a grain of salt", "относиться скептически", "Take his claims with a grain of salt."),
        ("the best of both worlds", "лучшее из двух миров", "Remote work is the best of both worlds."),
        ("tie the knot", "пожениться", "They tied the knot last summer."),
        ("up in the air", "под вопросом", "Plans are still up in the air."),
        ("when pigs fly", "когда рак на горе свистнет", "He'll apologize when pigs fly."),
        ("over the moon", "на седьмом небе", "She was over the moon about the promotion."),
        ("down to earth", "простой, приземлённый", "He's surprisingly down to earth."),
        ("head over heels", "по уши (влюбиться)", "He's head over heels for her."),
        ("once in a blue moon", "очень редко", "We meet once in a blue moon."),
        ("a blessing in disguise", "не было бы счастья…", "Losing that job was a blessing in disguise."),
        ("beat around the bush", "ходить вокруг да около", "Don't beat around the bush — get to the point."),
        ("cut to the chase", "ближе к делу", "Let me cut to the chase."),
        ("get cold feet", "струсить", "He got cold feet before the interview."),
        ("go back to the drawing board", "начать сначала", "The design failed — back to the drawing board."),
        ("hit the ground running", "с места в карьер", "She hit the ground running on day one."),
        ("kill two birds with one stone", "убить двух зайцев", "Let's kill two birds with one stone."),
        ("read between the lines", "читать между строк", "Read between the lines of his email."),
        ("step up to the plate", "взять на себя", "Someone needs to step up to the plate."),
        ("throw in the towel", "сдаться", "After 10 years, I threw in the towel."),
        ("turn a blind eye", "закрыть глаза на", "Management turned a blind eye to the bug."),
        ("wrap your head around", "осмыслить", "I can't wrap my head around this."),
        ("a dime a dozen", "пруд пруди", "Junior devs are a dime a dozen."),
        ("back to square one", "начинаем сначала", "Deal fell through — back to square one."),
        ("by the book", "строго по правилам", "She does everything by the book."),
        ("dressed to the nines", "разодет в пух и прах", "He showed up dressed to the nines."),
        ("get along", "ладить", "I get along with my colleagues."),
        ("hang in there", "держись", "Hang in there — it'll get better."),
        ("in a nutshell", "вкратце", "In a nutshell: ship it or cut it."),
        ("know the ropes", "знать все тонкости", "After a year, you'll know the ropes."),
        ("make a long story short", "короче говоря", "To make a long story short, we lost."),
        ("on the same wavelength", "на одной волне", "We're on the same wavelength."),
        ("play it by ear", "решать по ходу", "Let's play it by ear."),
        ("put two and two together", "сложить 2+2", "She put two and two together."),
        ("the last straw", "последняя капля", "That was the last straw."),
        ("through thick and thin", "и в горе и в радости", "They stuck together through thick and thin."),
        ("wear many hats", "совмещать много ролей", "In a startup, you wear many hats."),
        ("a no-brainer", "очевидное решение", "Accepting the offer was a no-brainer."),
        ("dead giveaway", "явный признак", "His accent was a dead giveaway."),
        ("easier said than done", "легче сказать, чем сделать", "Stay calm? Easier said than done."),
        ("food for thought", "пища для размышлений", "That's food for thought."),
        ("get the ball rolling", "запустить процесс", "Let's get the ball rolling."),
        ("give it a shot", "попытаться", "I'll give it a shot."),
        ("go with the flow", "плыть по течению", "Just go with the flow today."),
        ("hit the books", "засесть за учёбу", "Exam tomorrow — time to hit the books."),
        ("no pain, no gain", "без труда не вытащишь рыбку", "No pain, no gain at the gym."),
        ("pull strings", "использовать связи", "He pulled some strings to get in."),
        ("rule of thumb", "практическое правило", "As a rule of thumb, test first.")
    ]

    // MARK: - Phrasal Verbs Basic A2-B1 (~60)
    static let phrasalBasic: [Entry] = [
        ("get up", "вставать (утром)", "I get up at 7 every day."),
        ("wake up", "просыпаться", "I woke up late today."),
        ("sit down", "садиться", "Please sit down."),
        ("stand up", "вставать (подняться)", "Stand up when she enters."),
        ("come in", "входить", "Come in, the door is open."),
        ("go out", "выходить / гулять", "Let's go out tonight."),
        ("come back", "возвращаться", "When are you coming back?"),
        ("go back", "вернуться", "Go back to your seat."),
        ("turn on", "включить", "Turn on the lights."),
        ("turn off", "выключить", "Turn off the TV."),
        ("pick up", "поднять / забрать", "Pick up your clothes."),
        ("put down", "положить", "Put the bag down here."),
        ("put on", "надеть (одежду)", "Put on a jacket, it's cold."),
        ("take off", "снять (одежду) / взлетать", "Take off your shoes."),
        ("try on", "примерить", "Can I try on this shirt?"),
        ("look for", "искать", "I'm looking for my keys."),
        ("look at", "смотреть на", "Look at this picture."),
        ("look up", "посмотреть (в словаре/интернете)", "Look up the word."),
        ("find out", "узнать, выяснить", "I need to find out the truth."),
        ("give up", "сдаться, бросить", "Don't give up!"),
        ("give back", "вернуть", "Give me my book back."),
        ("throw away", "выбросить", "Throw away the old food."),
        ("clean up", "убрать, прибраться", "Clean up your room."),
        ("tidy up", "навести порядок", "Tidy up before guests come."),
        ("get on", "садиться (в транспорт)", "Get on the bus here."),
        ("get off", "выходить (из транспорта)", "Get off at the next stop."),
        ("get in", "садиться (в машину)", "Get in the car."),
        ("get out", "выйти (из машины)", "Get out of the car."),
        ("grow up", "вырасти", "I grew up in Moscow."),
        ("bring up", "воспитывать / поднять тему", "She was brought up by grandma."),
        ("hang out", "тусоваться", "Let's hang out this weekend."),
        ("hang up", "повесить трубку", "He hung up on me."),
        ("call back", "перезвонить", "I'll call you back later."),
        ("write down", "записать", "Write down the address."),
        ("fill in", "заполнить (форму)", "Fill in the form."),
        ("fill out", "заполнить (анкету)", "Fill out the application."),
        ("hand in", "сдать (работу)", "Hand in your homework."),
        ("hand out", "раздать", "Hand out the papers."),
        ("run out of", "закончиться (запасы)", "We ran out of milk."),
        ("pay back", "отдать долг", "I'll pay you back tomorrow."),
        ("slow down", "замедлиться", "Slow down, you're driving fast."),
        ("speed up", "ускориться", "Speed up, we're late."),
        ("break down", "сломаться", "The car broke down."),
        ("break up", "расстаться", "They broke up last month."),
        ("shut down", "выключить (систему)", "Shut down your computer."),
        ("set up", "установить, настроить", "Set up the new phone."),
        ("log in", "войти в аккаунт", "Log in with your email."),
        ("log out", "выйти из аккаунта", "Don't forget to log out."),
        ("sign up", "зарегистрироваться", "Sign up for the newsletter."),
        ("show up", "появиться, прийти", "He didn't show up."),
        ("eat out", "есть вне дома", "We eat out on Fridays."),
        ("take out", "вынести / заказать навынос", "Take out the trash."),
        ("work out", "тренироваться / получиться", "I work out three times a week."),
        ("figure out", "разобраться", "I'll figure it out."),
        ("point out", "указать, обратить внимание", "He pointed out the mistake."),
        ("check in", "зарегистрироваться (в отеле)", "Check in is at 3 PM."),
        ("check out", "выписаться / посмотреть", "Check out this cool app."),
        ("drop off", "высадить / отвезти", "Drop me off at the corner."),
        ("pick up", "подобрать / забрать кого-то", "I'll pick you up at 6."),
        ("cheer up", "подбодрить(ся)", "Cheer up, it's not that bad.")
    ]

    // MARK: - Phrasal Verbs Intermediate B1-B2 (~60)
    static let phrasalIntermediate: [Entry] = [
        ("bring about", "вызвать, привести к", "The new law brought about major changes."),
        ("bring up", "поднять тему", "Don't bring up politics at dinner."),
        ("call off", "отменить", "They called off the meeting."),
        ("calm down", "успокоиться", "Calm down and think clearly."),
        ("carry on", "продолжать", "Carry on with your work."),
        ("catch up with", "нагнать, догнать", "I need to catch up with the class."),
        ("come across", "натолкнуться, встретить случайно", "I came across an old photo."),
        ("come up with", "придумать", "She came up with a great idea."),
        ("count on", "рассчитывать на", "You can count on me."),
        ("cut down on", "сократить потребление", "Cut down on sugar."),
        ("deal with", "иметь дело, справляться", "I can't deal with this."),
        ("do without", "обойтись без", "I can't do without coffee."),
        ("dress up", "нарядиться", "Dress up for the party."),
        ("drop out", "бросить (учёбу)", "He dropped out of college."),
        ("end up", "оказаться в итоге", "We ended up staying home."),
        ("fall apart", "развалиться", "The plan fell apart."),
        ("fall behind", "отстать", "Don't fall behind on payments."),
        ("get along (with)", "ладить", "I get along with my neighbors."),
        ("get away", "сбежать / уехать отдохнуть", "Let's get away for the weekend."),
        ("get by", "обходиться, сводить концы", "I can get by on this salary."),
        ("get over", "пережить, оправиться", "He got over the flu quickly."),
        ("get rid of", "избавиться от", "Get rid of old clothes."),
        ("get through", "дозвониться / пережить", "I can't get through to her."),
        ("give away", "отдать бесплатно / выдать секрет", "Don't give away the ending."),
        ("give in", "уступить", "She finally gave in to his request."),
        ("go ahead", "продолжайте, начинайте", "Go ahead, I'm listening."),
        ("go on", "продолжать / происходить", "What's going on?"),
        ("go over", "просмотреть, проверить", "Go over the report one more time."),
        ("go through", "пройти через / просмотреть", "She's going through a tough time."),
        ("grow out of", "перерасти", "He'll grow out of it."),
        ("hold on", "подождать", "Hold on a second."),
        ("keep on", "продолжать (делать)", "Keep on trying."),
        ("keep up with", "не отставать от", "Hard to keep up with trends."),
        ("let down", "разочаровать", "Don't let me down."),
        ("live up to", "оправдать ожидания", "She lived up to the hype."),
        ("look after", "присматривать за", "Look after the kids."),
        ("look forward to", "с нетерпением ждать", "I look forward to the trip."),
        ("look into", "изучить, расследовать", "We'll look into it."),
        ("look out", "осторожно!", "Look out, there's a car!"),
        ("make up", "помириться / придумать", "They made up after the fight."),
        ("make up for", "компенсировать", "I'll make up for lost time."),
        ("move on", "двигаться дальше", "It's time to move on."),
        ("pass away", "скончаться", "His grandfather passed away."),
        ("pass out", "потерять сознание", "She passed out from heat."),
        ("pull over", "остановиться (на обочине)", "The cop told us to pull over."),
        ("put off", "откладывать", "Stop putting it off."),
        ("put up with", "терпеть, мириться с", "I can't put up with this noise."),
        ("run into", "случайно встретить", "I ran into her at the store."),
        ("run over", "переехать / быстро просмотреть", "Let me run over the agenda."),
        ("sort out", "разобраться, уладить", "We need to sort this out."),
        ("stand for", "означать / терпеть", "What does NASA stand for?"),
        ("stick to", "придерживаться", "Stick to the plan."),
        ("take after", "быть похожим (на родителя)", "She takes after her mom."),
        ("take over", "взять на себя / захватить", "Who will take over the project?"),
        ("talk into", "уговорить", "She talked me into going."),
        ("talk out of", "отговорить", "He talked me out of quitting."),
        ("turn down", "отклонить / убавить", "They turned down my offer."),
        ("turn into", "превратиться в", "The frog turned into a prince."),
        ("turn up", "появиться / прибавить", "He turned up late."),
        ("watch out", "осторожно!", "Watch out for pickpockets.")
    ]

    // MARK: - Phrasal Verbs Advanced (~70)
    static let phrasalAdvanced: [Entry] = [
        ("bear out", "подтверждать (утверждение)", "The data bears out our hypothesis."),
        ("bog down", "увязнуть, замедлить", "Meetings bog the team down."),
        ("brush up on", "освежить знания", "I'm brushing up on Japanese."),
        ("call off", "отменить", "They called off the merger."),
        ("carry on", "продолжать", "Carry on with the plan."),
        ("carry out", "выполнить", "Carry out the migration tonight."),
        ("catch up on", "наверстать", "I need to catch up on emails."),
        ("churn out", "клепать, штамповать", "The team churns out features weekly."),
        ("clamp down on", "пресекать, бороться с", "They clamped down on spam."),
        ("cobble together", "сколотить на коленке", "We cobbled together a fix."),
        ("come across as", "восприниматься как", "He comes across as arrogant."),
        ("come down to", "сводится к", "It comes down to priorities."),
        ("come up with", "придумать", "She came up with a brilliant idea."),
        ("cut back on", "сократить (расходы)", "We need to cut back on cloud costs."),
        ("dip into", "запустить руку (в запасы)", "Don't dip into the emergency fund."),
        ("draw up", "составить (документ)", "Draw up a proposal by Friday."),
        ("embark on", "начать (предприятие)", "Embark on the rewrite carefully."),
        ("end up with", "в итоге иметь", "We ended up with a workable MVP."),
        ("figure out", "разобраться, понять", "Figure out the bug before Monday."),
        ("fill in for", "подменить", "Can you fill in for me tomorrow?"),
        ("fizzle out", "сойти на нет", "The initiative fizzled out."),
        ("flesh out", "проработать детали", "Flesh out the design doc."),
        ("follow through on", "довести до конца", "Follow through on your promises."),
        ("gear up for", "готовиться к", "Gear up for launch week."),
        ("hammer out", "отработать детали", "Let's hammer out the contract."),
        ("hash out", "обсудить подробно", "Hash out the differences in 1:1."),
        ("hold off on", "повременить с", "Let's hold off on that purchase."),
        ("iron out", "сгладить, утрясти", "Iron out the bugs before release."),
        ("keep up with", "успевать, не отставать", "Hard to keep up with AI news."),
        ("lay off", "увольнять (сокращать)", "The company laid off 500 people."),
        ("level off", "стабилизироваться", "Traffic leveled off in April."),
        ("live up to", "оправдать ожидания", "Does it live up to the hype?"),
        ("look into", "изучить вопрос", "I'll look into it tomorrow."),
        ("make up for", "компенсировать", "Make up for it next sprint."),
        ("mull over", "обдумать", "Let me mull it over."),
        ("narrow down", "сузить (выбор)", "Narrow down the candidates to three."),
        ("opt out of", "отказаться от", "Opt out of marketing emails."),
        ("own up to", "признать (вину)", "He owned up to the mistake."),
        ("pass up", "упустить (возможность)", "Don't pass up this opportunity."),
        ("phase out", "постепенно вывести", "We're phasing out the legacy system."),
        ("pick up on", "уловить, заметить", "She picked up on the sarcasm."),
        ("pitch in", "помочь, подключиться", "Everyone pitched in during the crunch."),
        ("piece together", "собрать по кусочкам", "Piece together the logs."),
        ("press on", "упорствовать", "Despite failures, they pressed on."),
        ("prop up", "поддерживать (экономику)", "The government propped up the bank."),
        ("pull off", "провернуть, успешно сделать", "She pulled off a miracle."),
        ("push through", "пробиться, протолкнуть", "Push the change through before Q4."),
        ("put off", "откладывать", "Don't put off the hard stuff."),
        ("ramp up", "нарастить, усилить", "Ramp up hiring next quarter."),
        ("rattle off", "тараторить, перечислять бегло", "He rattled off a list of demands."),
        ("roll out", "раскатывать (релиз)", "We'll roll out to 10% first."),
        ("round off", "закруглить, завершить", "Round off with a Q&A."),
        ("rule out", "исключить", "Rule out hardware first."),
        ("run into", "столкнуться с", "I ran into Alex at the conference."),
        ("run out of", "закончиться", "We ran out of budget."),
        ("scale back", "урезать", "Scale back on ambitious features."),
        ("shrug off", "отмахнуться", "He shrugged off the criticism."),
        ("sort out", "разобраться, уладить", "Sort out the billing issue."),
        ("stand up to", "противостоять", "She stood up to the bully."),
        ("stem from", "проистекать из", "The issue stems from a race condition."),
        ("take apart", "разобрать (на части)", "Take apart the failing module."),
        ("take on", "взять на себя", "I'll take on the payment flow."),
        ("tap into", "задействовать (ресурс)", "Tap into the community's expertise."),
        ("tear down", "снести, демонтировать", "Tear down the old test environment."),
        ("think through", "продумать", "Think through the edge cases."),
        ("tie up", "завершать (дела)", "Tie up loose ends before leaving."),
        ("tone down", "приглушить", "Tone down the alerting."),
        ("toss out", "выбросить, отвергнуть", "Toss out the failed approach."),
        ("track down", "разыскать", "Track down the memory leak."),
        ("trim down", "урезать, подрезать", "Trim down the meeting list."),
        ("wave off", "отмахнуться", "He waved off my concerns."),
        ("weigh in on", "высказать мнение", "Weigh in on the RFC by Friday."),
        ("weigh up", "взвесить (варианты)", "Weigh up pros and cons."),
        ("wind up", "закончить (где-то)", "We wound up in Shibuya at 2am."),
        ("work around", "обойти (проблему)", "Work around the broken API for now."),
        ("zero in on", "сосредоточиться на", "Zero in on the root cause.")
    ]
}
