import Foundation

// Повседневные темы: тело, еда, эмоции, погода, дом + переезд (аренда, банк, медицина) + разное
struct EnglishLifeDecks {
    typealias Entry = (front: String, back: String, example: String)

    // MARK: - Тело: Мышцы (40)
    static let bodyMuscles: [Entry] = [
        ("biceps", "бицепсы", "Biceps curls work your arms."),
        ("triceps", "трицепсы", "Dips are great for triceps."),
        ("quads (quadriceps)", "квадрицепсы (передняя поверхность бедра)", "Squats target the quads."),
        ("hamstrings", "задняя поверхность бедра", "Stretch your hamstrings daily."),
        ("glutes", "ягодичные мышцы", "Hip thrusts activate the glutes."),
        ("calves", "икроножные мышцы", "Running builds strong calves."),
        ("abs (abdominals)", "пресс", "Six-pack abs require low body fat."),
        ("core", "кор, центральные мышцы", "A strong core stabilizes everything."),
        ("obliques", "косые мышцы живота", "Side planks hit the obliques."),
        ("lats (latissimus dorsi)", "широчайшие мышцы спины", "Pull-ups develop your lats."),
        ("traps (trapezius)", "трапеции", "Shrugs build the traps."),
        ("delts (deltoids)", "дельты, плечи", "Shoulder presses target delts."),
        ("pecs (pectorals)", "грудные мышцы", "Bench press builds pecs."),
        ("forearms", "предплечья", "Grip work develops forearms."),
        ("neck", "шея", "My neck is stiff from work."),
        ("spine", "позвоночник", "Good posture protects the spine."),
        ("lower back", "поясница", "Lower back pain is common."),
        ("upper back", "верх спины", "Rows target the upper back."),
        ("shoulder blade", "лопатка", "Retract your shoulder blades."),
        ("hip flexors", "подвздошно-поясничные (сгибатели бедра)", "Tight hip flexors cause back pain."),
        ("adductors", "приводящие (внутренняя поверхность бедра)", "Sumo squats hit adductors."),
        ("abductors", "отводящие (боковые ягодицы)", "Clamshells target abductors."),
        ("rotator cuff", "вращательная манжета плеча", "A torn rotator cuff sidelines athletes."),
        ("tendon", "сухожилие", "Achilles tendon injury hurts."),
        ("ligament", "связка", "ACL is a knee ligament."),
        ("muscle fiber", "мышечное волокно", "Training damages muscle fibers."),
        ("cramp", "судорога", "I got a cramp in my calf."),
        ("soreness", "крепатура, боль в мышцах", "Soreness peaks 48h after training."),
        ("DOMS", "отложенная мышечная боль", "DOMS = delayed onset muscle soreness."),
        ("stretch", "растягивать(ся)", "Stretch before and after workouts."),
        ("flex", "напрягать мышцу", "Flex your biceps."),
        ("contract", "сокращаться (о мышце)", "Muscles contract when activated."),
        ("range of motion", "амплитуда движения", "Full range of motion matters."),
        ("muscle mass", "мышечная масса", "Protein supports muscle mass."),
        ("strength", "сила", "Strength training beats cardio for fat loss."),
        ("endurance", "выносливость", "Long runs build endurance."),
        ("flexibility", "гибкость", "Yoga improves flexibility."),
        ("mobility", "мобильность", "Mobility work prevents injury."),
        ("atrophy", "атрофия мышц", "Bed rest causes muscle atrophy."),
        ("hypertrophy", "гипертрофия (рост мышц)", "Hypertrophy needs progressive overload.")
    ]

    // MARK: - Тело: Кости и органы (35)
    static let bodyOrgans: [Entry] = [
        ("bone", "кость", "I broke a bone in my wrist."),
        ("skull", "череп", "The skull protects the brain."),
        ("rib", "ребро", "I cracked a rib."),
        ("rib cage", "грудная клетка", "The rib cage houses the lungs."),
        ("pelvis", "таз", "The pelvis connects legs to spine."),
        ("collarbone", "ключица", "She broke her collarbone skiing."),
        ("jaw", "челюсть", "Clenching your jaw causes headaches."),
        ("joint", "сустав", "My joints ache in cold weather."),
        ("knee", "колено", "My knee clicks when I squat."),
        ("elbow", "локоть", "Tennis elbow is a tendon issue."),
        ("ankle", "лодыжка", "I twisted my ankle."),
        ("wrist", "запястье", "Typing strains the wrist."),
        ("heart", "сердце", "Cardio strengthens the heart."),
        ("lungs", "лёгкие", "Deep breaths fill the lungs."),
        ("liver", "печень", "Alcohol stresses the liver."),
        ("kidneys", "почки", "Drink water to support kidneys."),
        ("stomach", "желудок", "My stomach is rumbling."),
        ("intestines", "кишечник", "Fiber helps the intestines."),
        ("bladder", "мочевой пузырь", "Caffeine irritates the bladder."),
        ("brain", "мозг", "Sleep consolidates brain memories."),
        ("nerve", "нерв", "A pinched nerve causes shooting pain."),
        ("vein", "вена", "Veins carry blood back to the heart."),
        ("artery", "артерия", "Clogged arteries risk heart attack."),
        ("blood vessel", "кровеносный сосуд", "Exercise widens blood vessels."),
        ("skin", "кожа", "Dry skin needs moisturizer."),
        ("cartilage", "хрящ", "Knee cartilage wears down with age."),
        ("spinal cord", "спинной мозг", "Spinal cord injuries are severe."),
        ("gut", "кишечник (разг.) / нутро", "Trust your gut."),
        ("throat", "горло", "My throat is sore."),
        ("tongue", "язык (орган)", "I bit my tongue."),
        ("gums", "дёсны", "Bleeding gums may mean gingivitis."),
        ("eyelid", "веко", "My eyelid is twitching."),
        ("eyebrow", "бровь", "She raised an eyebrow skeptically."),
        ("earlobe", "мочка уха", "She pierced her earlobe."),
        ("knuckle", "костяшка", "He cracked his knuckles.")
    ]

    // MARK: - Тело: Спортзал (40)
    static let bodyGym: [Entry] = [
        ("workout", "тренировка", "I had a tough workout."),
        ("rep (repetition)", "повторение", "Do 10 reps of each exercise."),
        ("set", "подход", "Three sets of twelve reps."),
        ("warm-up", "разминка", "Never skip the warm-up."),
        ("cool-down", "заминка", "Stretching is a good cool-down."),
        ("cardio", "кардио", "Run 30 minutes of cardio."),
        ("strength training", "силовые", "Strength training twice a week."),
        ("HIIT", "интервальная тренировка", "HIIT burns fat fast."),
        ("dumbbell", "гантель", "Pick up a 20 lb dumbbell."),
        ("barbell", "штанга", "Load the barbell with plates."),
        ("kettlebell", "гиря", "Kettlebell swings are explosive."),
        ("plate", "блин (для штанги)", "Add two plates per side."),
        ("treadmill", "беговая дорожка", "The treadmill is free."),
        ("elliptical", "эллиптический тренажёр", "Low-impact on elliptical."),
        ("rowing machine", "гребной тренажёр", "Rowing works full body."),
        ("pull-up bar", "перекладина", "Install a pull-up bar at home."),
        ("bench", "скамья", "Adjustable bench is versatile."),
        ("mat", "коврик", "Bring your yoga mat."),
        ("resistance band", "эспандер", "Resistance bands travel well."),
        ("squat", "приседание", "Barbell squats are the king."),
        ("deadlift", "становая тяга", "Deadlift teaches hip hinge."),
        ("bench press", "жим лёжа", "Bench press builds chest."),
        ("overhead press", "жим над головой", "Overhead press needs core strength."),
        ("row", "тяга", "Barbell row hits the back."),
        ("pull-up", "подтягивание", "Pull-ups are hard."),
        ("push-up", "отжимание", "Push-ups anywhere, no gear."),
        ("lunge", "выпад", "Walking lunges burn the legs."),
        ("plank", "планка", "Hold a plank for 60 seconds."),
        ("burpee", "бёрпи", "Burpees are brutal."),
        ("crunch", "скручивание", "Crunches aren't enough for abs."),
        ("PR (personal record)", "личный рекорд", "New PR on deadlift!"),
        ("one-rep max", "одноповторный максимум", "1RM testing is advanced."),
        ("progressive overload", "прогрессия нагрузки", "Progressive overload drives growth."),
        ("form", "техника выполнения", "Bad form leads to injury."),
        ("spotter", "страхующий", "I need a spotter for bench."),
        ("gym", "спортзал", "I go to the gym daily."),
        ("locker room", "раздевалка", "Leave your stuff in the locker room."),
        ("personal trainer", "личный тренер", "A trainer fixes your form."),
        ("gains", "прирост (мышц/силы)", "Gains require consistency."),
        ("rest day", "день отдыха", "Rest days aren't optional.")
    ]

    // MARK: - Еда: Продукты (60)
    static let foodGroceries: [Entry] = [
        ("beef", "говядина", "I prefer grass-fed beef."),
        ("pork", "свинина", "Pork chops are quick to cook."),
        ("lamb", "баранина", "Lamb pairs with rosemary."),
        ("chicken breast", "куриная грудка", "Chicken breast is lean protein."),
        ("chicken thigh", "куриное бедро", "Thighs are juicier than breast."),
        ("sirloin", "филей, филейная часть", "Sirloin steak for dinner."),
        ("ribeye", "рибай", "Ribeye is marbled and rich."),
        ("tenderloin", "вырезка", "Beef tenderloin is premium."),
        ("brisket", "грудинка", "Smoked brisket takes 12 hours."),
        ("ground beef", "говяжий фарш", "Ground beef for burgers."),
        ("minced meat", "фарш", "Minced meat for meatballs."),
        ("bacon", "бекон", "Crispy bacon with eggs."),
        ("ham", "ветчина", "Sliced ham for sandwiches."),
        ("sausage", "колбаса, сосиска", "German sausage on the grill."),
        ("salmon", "лосось", "Grilled salmon is healthy."),
        ("tuna", "тунец", "Canned tuna for salads."),
        ("cod", "треска", "Cod is mild and flaky."),
        ("shrimp", "креветки", "Shrimp cook in minutes."),
        ("squid", "кальмар", "Fried squid rings."),
        ("scallops", "гребешки", "Pan-seared scallops."),
        ("broccoli", "брокколи", "Steam the broccoli lightly."),
        ("cauliflower", "цветная капуста", "Roasted cauliflower is amazing."),
        ("spinach", "шпинат", "Baby spinach in salads."),
        ("kale", "кале, кудрявая капуста", "Kale is superfood hype."),
        ("lettuce", "салат-латук", "Iceberg lettuce for crunch."),
        ("cabbage", "капуста", "Shredded cabbage for slaw."),
        ("bell pepper", "болгарский перец", "Red bell pepper is sweetest."),
        ("cucumber", "огурец", "Chilled cucumber is refreshing."),
        ("zucchini", "цуккини, кабачок", "Zucchini grows huge."),
        ("eggplant", "баклажан", "Grilled eggplant with olive oil."),
        ("onion", "лук", "Dice the onion finely."),
        ("garlic", "чеснок", "Crush the garlic cloves."),
        ("ginger", "имбирь", "Fresh ginger root."),
        ("potato", "картошка", "Mashed potatoes tonight."),
        ("sweet potato", "сладкий картофель, батат", "Baked sweet potato fries."),
        ("carrot", "морковь", "Shred carrots for the salad."),
        ("celery", "сельдерей", "Celery sticks with peanut butter."),
        ("mushroom", "гриб", "Sautéed mushrooms."),
        ("rice", "рис", "Jasmine rice pairs well."),
        ("pasta", "паста, макароны", "Al dente pasta."),
        ("oats", "овсянка", "Oats for breakfast."),
        ("quinoa", "киноа", "Quinoa is a complete protein."),
        ("lentils", "чечевица", "Red lentils cook fast."),
        ("chickpeas", "нут", "Chickpeas for hummus."),
        ("beans", "фасоль", "Black beans and rice."),
        ("flour", "мука", "Sift the flour."),
        ("sugar", "сахар", "Two tablespoons of sugar."),
        ("salt", "соль", "Salt to taste."),
        ("pepper (black)", "чёрный перец", "Freshly cracked pepper."),
        ("paprika", "паприка", "Smoked paprika has depth."),
        ("cinnamon", "корица", "Cinnamon on oatmeal."),
        ("nutmeg", "мускатный орех", "A pinch of nutmeg."),
        ("oregano", "орегано", "Italian seasoning has oregano."),
        ("basil", "базилик", "Fresh basil on pizza."),
        ("cilantro", "кинза", "Chop the cilantro."),
        ("olive oil", "оливковое масло", "Extra virgin olive oil."),
        ("butter", "сливочное масло", "Melt the butter."),
        ("cheese", "сыр", "Grate the cheese."),
        ("yogurt", "йогурт", "Greek yogurt is thick."),
        ("milk", "молоко", "Whole milk vs. skim."),
        ("eggs", "яйца", "Scrambled eggs for breakfast.")
    ]

    // MARK: - Еда: Готовка (40)
    static let foodCooking: [Entry] = [
        ("fry", "жарить на сковороде", "Fry the onions first."),
        ("deep-fry", "жарить во фритюре", "Deep-fry until golden."),
        ("pan-fry", "обжаривать на сковороде", "Pan-fry the steak."),
        ("stir-fry", "обжаривать помешивая", "Stir-fry the veggies."),
        ("sauté", "пассеровать, быстро обжаривать", "Sauté the mushrooms."),
        ("bake", "печь (в духовке)", "Bake at 350°F."),
        ("roast", "запекать (мясо, овощи)", "Roast the chicken for an hour."),
        ("broil", "готовить под верхним грилем", "Broil the fish briefly."),
        ("grill", "жарить на гриле", "Grill the burgers."),
        ("boil", "варить, кипятить", "Boil the water first."),
        ("simmer", "томить, варить на медленном огне", "Simmer the sauce for 30 minutes."),
        ("steam", "готовить на пару", "Steam the broccoli."),
        ("poach", "варить в горячей воде (яйцо, рыба)", "Poach the eggs gently."),
        ("braise", "тушить (сначала обжарить, потом тушить)", "Braised short ribs."),
        ("stew", "тушить долго", "Beef stew cooks for hours."),
        ("smoke", "коптить", "Smoke the salmon."),
        ("marinate", "мариновать", "Marinate overnight."),
        ("season", "приправить", "Season with salt and pepper."),
        ("garnish", "украшать блюдо", "Garnish with parsley."),
        ("chop", "рубить, крошить", "Chop the onion."),
        ("dice", "нарезать кубиками", "Dice the tomatoes."),
        ("mince", "мелко порубить", "Mince the garlic."),
        ("slice", "нарезать ломтиками", "Slice the bread."),
        ("julienne", "нарезать соломкой", "Julienne the carrots."),
        ("grate", "тереть на тёрке", "Grate the cheese."),
        ("peel", "чистить (кожуру)", "Peel the potatoes."),
        ("whisk", "взбивать венчиком", "Whisk the eggs."),
        ("beat", "взбивать", "Beat until stiff peaks."),
        ("fold", "осторожно смешивать (вмешивать)", "Fold in the egg whites."),
        ("knead", "месить (тесто)", "Knead the dough for 10 minutes."),
        ("drizzle", "полить тонкой струйкой", "Drizzle with olive oil."),
        ("sprinkle", "посыпать", "Sprinkle cinnamon on top."),
        ("melt", "растопить", "Melt the butter."),
        ("preheat", "предварительно нагреть", "Preheat the oven."),
        ("let it rest", "дать постоять (мясу)", "Let the steak rest 5 minutes."),
        ("caramelize", "карамелизировать", "Caramelize the onions slowly."),
        ("reduce", "уваривать, выпаривать", "Reduce the sauce by half."),
        ("thicken", "загустить", "Thicken with a cornstarch slurry."),
        ("blend", "смешать в блендере", "Blend until smooth."),
        ("puree", "пюрировать", "Puree the soup.")
    ]

    // MARK: - Еда: Кухонная утварь (30)
    static let foodKitchen: [Entry] = [
        ("knife", "нож", "A sharp knife is safer."),
        ("chef's knife", "шеф-нож", "Chef's knife for most tasks."),
        ("cutting board", "разделочная доска", "Wooden cutting board."),
        ("pan", "сковорода", "Heat the pan first."),
        ("skillet", "сковорода (глубокая)", "Cast iron skillet."),
        ("pot", "кастрюля", "Big pot for pasta."),
        ("saucepan", "сотейник", "Saucepan for sauces."),
        ("wok", "вок", "Wok for stir-fry."),
        ("baking sheet", "противень", "Line the baking sheet."),
        ("casserole dish", "форма для запекания", "Casserole dish for lasagna."),
        ("whisk", "венчик", "Whisk for whipping."),
        ("spatula", "лопатка (кухонная)", "Silicone spatula."),
        ("tongs", "щипцы", "Tongs to flip the steak."),
        ("ladle", "половник", "Serve soup with a ladle."),
        ("slotted spoon", "шумовка", "Slotted spoon to drain."),
        ("grater", "тёрка", "Box grater for cheese."),
        ("peeler", "овощечистка", "Vegetable peeler."),
        ("colander", "дуршлаг", "Drain pasta in a colander."),
        ("sieve", "сито", "Sift flour through a sieve."),
        ("rolling pin", "скалка", "Roll dough with a rolling pin."),
        ("measuring cup", "мерный стакан", "Measuring cup for flour."),
        ("measuring spoons", "мерные ложки", "Measuring spoons for accuracy."),
        ("kitchen scale", "кухонные весы", "Use a scale for baking."),
        ("blender", "блендер", "High-speed blender."),
        ("food processor", "кухонный комбайн", "Food processor chops fast."),
        ("stand mixer", "планетарный миксер", "KitchenAid stand mixer."),
        ("microwave", "микроволновка", "Heat in the microwave."),
        ("oven", "духовка", "Preheat the oven."),
        ("stove / cooktop", "плита / варочная панель", "Gas stove is precise."),
        ("dishwasher", "посудомойка", "Load the dishwasher.")
    ]

    // MARK: - Эмоции (60)
    static let emotions: [Entry] = [
        ("overwhelmed", "перегружен, подавлен", "I'm overwhelmed with work."),
        ("frustrated", "раздражён, расстроен", "Traffic makes me frustrated."),
        ("anxious", "тревожный", "I feel anxious before exams."),
        ("relieved", "испытывающий облегчение", "I was relieved to hear the news."),
        ("grateful", "благодарный", "I'm grateful for your help."),
        ("envious", "завистливый", "I was envious of her trip."),
        ("jealous", "ревнивый", "Don't be jealous."),
        ("content", "довольный", "I feel content after a good meal."),
        ("cheerful", "радостный, весёлый", "She's always cheerful."),
        ("gloomy", "мрачный, угрюмый", "Rainy days make me gloomy."),
        ("moody", "переменчивого настроения", "He's moody in the mornings."),
        ("restless", "беспокойный, не находит места", "I'm restless tonight."),
        ("agitated", "взволнованный, возбуждённый", "He seemed agitated during the meeting."),
        ("startled", "испуганный (внезапно)", "I was startled by the noise."),
        ("stunned", "ошеломлён", "I'm stunned by the decision."),
        ("flattered", "польщён", "I'm flattered by the compliment."),
        ("humiliated", "униженный", "He felt humiliated after the fall."),
        ("embarrassed", "смущён", "I was embarrassed in front of everyone."),
        ("proud", "гордый", "I'm proud of you."),
        ("ashamed", "пристыжён", "She was ashamed of her actions."),
        ("guilty", "виноватый", "I feel guilty for missing it."),
        ("regretful", "сожалеющий", "I'm regretful about my choice."),
        ("hopeful", "полон надежд", "I'm hopeful about the outcome."),
        ("hopeless", "безнадёжный", "Don't feel hopeless."),
        ("helpless", "беспомощный", "I felt helpless watching it unfold."),
        ("confused", "в замешательстве", "I'm confused by the instructions."),
        ("curious", "любопытный", "I'm curious about this project."),
        ("intrigued", "заинтригован", "I'm intrigued by the idea."),
        ("skeptical", "скептичный", "I'm skeptical of the claims."),
        ("resentful", "обиженный, затаивший злобу", "She's resentful of her sister."),
        ("bitter", "озлобленный", "He's bitter about the breakup."),
        ("thrilled", "в восторге", "I'm thrilled about the promotion."),
        ("excited", "взволнованный (позитивно)", "Kids are excited for the trip."),
        ("eager", "жаждущий, рвущийся", "I'm eager to start."),
        ("reluctant", "неохотный", "He was reluctant to answer."),
        ("hesitant", "нерешительный", "I'm hesitant to commit."),
        ("confident", "уверенный", "She walked in confident."),
        ("insecure", "неуверенный в себе", "He's insecure about his accent."),
        ("vulnerable", "уязвимый", "Opening up feels vulnerable."),
        ("defensive", "в защитной позиции", "Don't get defensive."),
        ("indifferent", "равнодушный", "He seemed indifferent to the news."),
        ("numb", "онемевший, бесчувственный", "I feel numb after the shock."),
        ("exhausted", "изнурённый", "I'm exhausted after the trip."),
        ("drained", "выжат, измотан", "Meetings leave me drained."),
        ("energized", "полон энергии", "I feel energized after coffee."),
        ("refreshed", "освежённый", "A nap leaves me refreshed."),
        ("tense", "напряжённый", "She looks tense."),
        ("relaxed", "расслабленный", "I feel relaxed on weekends."),
        ("at ease", "расслаблен, в своей тарелке", "He puts everyone at ease."),
        ("on edge", "на взводе, нервничает", "I've been on edge all day."),
        ("nostalgic", "ностальгирующий", "Old songs make me nostalgic."),
        ("homesick", "скучающий по дому", "First-year students get homesick."),
        ("lonely", "одинокий", "Remote work can be lonely."),
        ("isolated", "изолирован", "He felt isolated after the move."),
        ("supported", "поддерживаемый", "I felt supported by the team."),
        ("appreciated", "оценённый", "She felt appreciated."),
        ("underappreciated", "недооценённый", "He feels underappreciated at work."),
        ("betrayed", "преданный", "He felt betrayed by his friend."),
        ("disillusioned", "разочарованный", "I'm disillusioned with politics."),
        ("fulfilled", "реализованный (чувство)", "I feel fulfilled in this role.")
    ]

    // MARK: - Погода и природа (50)
    static let weather: [Entry] = [
        ("sunny", "солнечный", "It's sunny today."),
        ("cloudy", "облачный", "Cloudy but no rain."),
        ("overcast", "пасмурный", "The sky is overcast."),
        ("clear skies", "ясное небо", "Clear skies all weekend."),
        ("rain", "дождь", "Heavy rain expected."),
        ("drizzle", "моросящий дождь", "Just a light drizzle."),
        ("downpour", "ливень", "Caught in a downpour."),
        ("shower", "кратковременный дождь", "Afternoon showers likely."),
        ("thunderstorm", "гроза", "Thunderstorms all evening."),
        ("lightning", "молния", "Lightning flashed over the lake."),
        ("thunder", "гром", "Thunder rolled across the valley."),
        ("snow", "снег", "First snow of winter."),
        ("snowstorm", "снежная буря, метель", "The snowstorm closed schools."),
        ("blizzard", "пурга, буран", "Blizzard conditions up north."),
        ("sleet", "ледяной дождь, крупа", "Sleet makes driving dangerous."),
        ("hail", "град", "Hail damaged the cars."),
        ("fog", "туман", "Dense fog delayed flights."),
        ("mist", "дымка, лёгкий туман", "Morning mist on the field."),
        ("frost", "иней, заморозки", "Frost on the windshield."),
        ("breeze", "лёгкий ветерок", "A cool breeze off the ocean."),
        ("gust", "порыв ветра", "A sudden gust knocked me over."),
        ("wind", "ветер", "Strong winds overnight."),
        ("windy", "ветрено", "It's windy at the coast."),
        ("calm", "безветренный, тихий", "A calm, still evening."),
        ("humid", "влажный, душный", "Tokyo is humid in summer."),
        ("dry", "сухой", "Dry heat in the desert."),
        ("muggy", "душный, липкий", "A muggy August afternoon."),
        ("chilly", "прохладный", "Chilly evening, grab a jacket."),
        ("mild", "мягкий (о погоде)", "Mild winter this year."),
        ("scorching", "палящий", "Scorching heat in Arizona."),
        ("freezing", "ледяной, морозный", "Freezing temperatures tonight."),
        ("heatwave", "волна жары", "A heatwave hit Europe."),
        ("cold snap", "резкое похолодание", "Cold snap expected mid-week."),
        ("temperature", "температура", "Temperature dropped 20 degrees."),
        ("forecast", "прогноз погоды", "Check the forecast."),
        ("sunrise", "восход", "Sunrise at 6:14."),
        ("sunset", "закат", "Gorgeous sunset tonight."),
        ("dusk", "сумерки (вечер)", "Walk before dusk."),
        ("dawn", "рассвет", "Birds sing at dawn."),
        ("mountain", "гора", "Hike the mountain trail."),
        ("hill", "холм", "Rolling hills of Tuscany."),
        ("valley", "долина", "Vineyards fill the valley."),
        ("cliff", "утёс, обрыв", "Dover's white cliffs."),
        ("meadow", "луг", "A meadow of wildflowers."),
        ("forest", "лес", "Deep in the forest."),
        ("stream", "ручей", "A clear mountain stream."),
        ("river", "река", "The river is flooding."),
        ("lake", "озеро", "Swimming in the lake."),
        ("shore", "берег (моря, озера)", "Waves on the shore."),
        ("dune", "дюна", "Sand dunes in the desert.")
    ]

    // MARK: - Дом и быт (60)
    static let home: [Entry] = [
        ("living room", "гостиная", "We have guests in the living room."),
        ("bedroom", "спальня", "The bedroom is upstairs."),
        ("kitchen", "кухня", "I spend hours in the kitchen."),
        ("bathroom", "ванная / туалет", "Where's the bathroom?"),
        ("hallway", "коридор, прихожая", "Shoes go in the hallway."),
        ("entryway", "прихожая (при входе)", "Drop your keys in the entryway."),
        ("attic", "чердак", "Old stuff is in the attic."),
        ("basement", "подвал", "Our basement floods in spring."),
        ("garage", "гараж", "Park in the garage."),
        ("balcony", "балкон", "Coffee on the balcony."),
        ("porch", "крыльцо, веранда", "Rocking chair on the porch."),
        ("yard", "двор", "Play in the yard."),
        ("closet", "шкаф-кладовка / встроенный шкаф", "Walk-in closet."),
        ("couch / sofa", "диван", "Nap on the couch."),
        ("armchair", "кресло", "Leather armchair."),
        ("ottoman", "пуф", "Leather ottoman for your feet."),
        ("coffee table", "журнальный столик", "Books pile on the coffee table."),
        ("bookshelf", "книжный шкаф", "Books overflow the bookshelf."),
        ("nightstand", "прикроватная тумбочка", "Lamp on the nightstand."),
        ("dresser", "комод (в спальне)", "Socks in the dresser drawer."),
        ("vanity", "туалетный столик", "Makeup at the vanity."),
        ("wardrobe", "гардероб, шкаф", "Reorganize the wardrobe."),
        ("console (table)", "консольный столик", "Keys on the console table."),
        ("built-in", "встроенная (мебель)", "Built-in shelves save space."),
        ("cabinet", "шкафчик (на кухне)", "Dishes in the upper cabinet."),
        ("countertop", "столешница", "Granite countertop."),
        ("sink", "раковина", "Dishes piled in the sink."),
        ("faucet", "кран", "The faucet is dripping."),
        ("stove / oven", "плита / духовка", "Turn off the stove."),
        ("fridge / refrigerator", "холодильник", "Put it in the fridge."),
        ("freezer", "морозилка", "Ice cream in the freezer."),
        ("dishwasher", "посудомойка", "Load the dishwasher."),
        ("washing machine", "стиральная машина", "Washing machine broke again."),
        ("dryer", "сушилка (для белья)", "Dryer's almost done."),
        ("vacuum (cleaner)", "пылесос", "Vacuum the rugs."),
        ("blender", "блендер", "Smoothie in the blender."),
        ("kettle", "чайник (электрический)", "Put the kettle on."),
        ("toaster", "тостер", "Pop-up toaster."),
        ("microwave", "микроволновка", "Heat it in the microwave."),
        ("air conditioner / AC", "кондиционер", "Turn on the AC."),
        ("heater", "обогреватель", "Space heater in winter."),
        ("thermostat", "термостат", "Set the thermostat to 70."),
        ("lightbulb", "лампочка", "Replace the lightbulb."),
        ("outlet / socket", "розетка", "Plug into the outlet."),
        ("plug", "вилка, штепсель", "The plug doesn't fit."),
        ("extension cord", "удлинитель", "Grab an extension cord."),
        ("switch", "выключатель", "Flip the light switch."),
        ("pipe", "труба", "A pipe burst in the wall."),
        ("leak", "течь, утечка", "There's a leak under the sink."),
        ("drain", "слив", "Clear the drain."),
        ("clog", "засор", "Unclog the drain."),
        ("plunger", "вантуз", "Use the plunger."),
        ("mop", "швабра", "Mop the floor."),
        ("broom", "метла", "Sweep with the broom."),
        ("trash can / bin", "мусорка", "Take out the trash."),
        ("garbage / trash", "мусор", "Throw it in the garbage."),
        ("recycling bin", "контейнер для переработки", "Recyclables only."),
        ("curtain", "штора", "Close the curtains."),
        ("blinds", "жалюзи", "Open the blinds."),
        ("doormat", "коврик у двери", "Wipe your feet on the doormat."),
        ("rug", "ковёр (небольшой)", "Area rug in the living room.")
    ]

    // MARK: - Аренда (35)
    static let rental: [Entry] = [
        ("rent", "арендная плата / снимать", "Rent is due on the 1st."),
        ("lease", "договор аренды / арендовать (длительно)", "Signed a 1-year lease."),
        ("landlord", "арендодатель", "My landlord raised the rent."),
        ("tenant", "арендатор", "Quiet tenants are a blessing."),
        ("roommate", "сосед по квартире", "My roommate is moving out."),
        ("sublet", "сдавать в субаренду", "Sublet for the summer."),
        ("deposit / security deposit", "залог", "First month + security deposit."),
        ("utilities", "коммунальные услуги", "Rent includes utilities."),
        ("electricity", "электричество", "Electricity is separate."),
        ("gas", "газ", "Gas bill was high this month."),
        ("water bill", "счёт за воду", "The water bill is low."),
        ("internet / Wi-Fi", "интернет", "Internet is on the landlord."),
        ("heating", "отопление", "Central heating included."),
        ("apartment / flat", "квартира", "One-bedroom apartment."),
        ("studio", "студия", "A small studio downtown."),
        ("one-bedroom", "однокомнатная (с одной спальней)", "One-bedroom, 600 sqft."),
        ("furnished", "с мебелью", "Fully furnished unit."),
        ("unfurnished", "без мебели", "Unfurnished — bring your own."),
        ("utilities included", "с коммуналкой", "Utilities included, $1500/mo."),
        ("move-in date", "дата заезда", "Move-in date is June 1."),
        ("move-out", "выезд", "Move-out inspection tomorrow."),
        ("viewing / showing", "осмотр (квартиры)", "Viewing is at 3 PM."),
        ("application fee", "сбор за подачу заявки", "Non-refundable application fee."),
        ("credit check", "проверка кредитной истории", "Landlord ran a credit check."),
        ("background check", "проверка биографии", "Background check is standard."),
        ("co-signer / guarantor", "поручитель", "I need a co-signer."),
        ("lease agreement", "договор аренды", "Read the lease agreement carefully."),
        ("renewal", "продление", "Lease renewal next month."),
        ("eviction", "выселение", "Eviction notice is serious."),
        ("notice period", "срок уведомления", "60-day notice period."),
        ("pet policy", "правила по питомцам", "No-pet policy, sorry."),
        ("pet deposit", "депозит за питомца", "$500 pet deposit."),
        ("parking spot", "парковочное место", "Parking spot included."),
        ("amenities", "удобства", "Amenities: gym, pool, rooftop."),
        ("HOA fee", "взнос в ТСЖ", "HOA fee covers maintenance.")
    ]

    // MARK: - Банк и финансы (40)
    static let banking: [Entry] = [
        ("checking account", "расчётный счёт", "Open a checking account."),
        ("savings account", "сберегательный счёт", "Savings account earns interest."),
        ("balance", "баланс на счёте", "Check your balance."),
        ("statement", "выписка", "Monthly statement."),
        ("transaction", "транзакция", "Every transaction is logged."),
        ("deposit", "вклад / внести", "Make a deposit at the ATM."),
        ("withdrawal", "снятие", "Cash withdrawal limit."),
        ("transfer", "перевод", "Transfer between accounts."),
        ("wire transfer", "банковский перевод (SWIFT)", "International wire transfer."),
        ("ACH transfer", "электронный перевод (внутри US)", "ACH is free but slow."),
        ("direct deposit", "прямое зачисление (зарплаты)", "Salary via direct deposit."),
        ("debit card", "дебетовая карта", "Pay with debit card."),
        ("credit card", "кредитная карта", "Credit card rewards."),
        ("credit limit", "кредитный лимит", "My credit limit is $5000."),
        ("credit score", "кредитный рейтинг", "A high credit score helps."),
        ("credit history", "кредитная история", "Build your credit history."),
        ("interest rate", "процентная ставка", "The interest rate is 5%."),
        ("APR", "годовая процентная ставка", "APR on this card is 22%."),
        ("fee", "комиссия", "Monthly maintenance fee."),
        ("overdraft", "овердрафт, минус на счёте", "Avoid overdraft fees."),
        ("overdraft fee", "комиссия за овердрафт", "$35 overdraft fee."),
        ("ATM", "банкомат", "Find an in-network ATM."),
        ("ATM fee", "комиссия банкомата", "Out-of-network ATM fee."),
        ("PIN", "ПИН-код", "Don't share your PIN."),
        ("routing number", "маршрутный номер (банка)", "Need the routing number."),
        ("account number", "номер счёта", "Never share your account number."),
        ("loan", "кредит", "Student loan payments."),
        ("mortgage", "ипотека", "30-year mortgage."),
        ("down payment", "первоначальный взнос", "20% down payment."),
        ("refinance", "рефинансировать", "Refinance at a lower rate."),
        ("budget", "бюджет", "Stick to your budget."),
        ("expense", "расход", "Track every expense."),
        ("income", "доход", "Monthly income."),
        ("invoice", "счёт-фактура", "Send me an invoice."),
        ("receipt", "чек", "Keep the receipt."),
        ("tax return", "налоговая декларация", "File your tax return."),
        ("deduction", "вычет", "Mortgage interest deduction."),
        ("refund", "возврат", "Tax refund came in."),
        ("pay stub / payslip", "расчётный листок", "Three months of pay stubs."),
        ("gross income", "доход до вычетов", "Gross income vs net.")
    ]

    // MARK: - У врача (45)
    static let medical: [Entry] = [
        ("appointment", "приём, визит", "Schedule an appointment."),
        ("check-up", "медосмотр", "Annual check-up."),
        ("walk-in", "приём без записи", "Walk-in clinic open till 8."),
        ("urgent care", "неотложная помощь (амбулаторная)", "Go to urgent care for cuts."),
        ("ER (emergency room)", "скорая / приёмный покой", "ER visit at 2 AM."),
        ("referral", "направление (к специалисту)", "I need a referral."),
        ("specialist", "узкий специалист", "See a specialist."),
        ("GP (general practitioner)", "терапевт", "Call your GP first."),
        ("primary care doctor", "лечащий врач", "Primary care doctor."),
        ("dentist", "стоматолог", "Twice-a-year dentist visit."),
        ("pediatrician", "педиатр", "Pediatrician for the kids."),
        ("prescription", "рецепт", "Pick up your prescription."),
        ("over-the-counter (OTC)", "безрецептурный", "Ibuprofen is over-the-counter."),
        ("pharmacy", "аптека", "The pharmacy is on the corner."),
        ("pharmacist", "фармацевт", "Ask the pharmacist."),
        ("dose", "доза", "Take the correct dose."),
        ("side effect", "побочный эффект", "Drowsiness is a side effect."),
        ("allergy", "аллергия", "I have a nut allergy."),
        ("allergic reaction", "аллергическая реакция", "Severe allergic reaction."),
        ("symptom", "симптом", "List your symptoms."),
        ("diagnosis", "диагноз", "Wait for the diagnosis."),
        ("treatment", "лечение", "Treatment plan discussed."),
        ("insurance", "страховка", "Show your insurance card."),
        ("copay", "доплата (пациента)", "$30 copay per visit."),
        ("deductible", "франшиза", "Annual deductible is $2000."),
        ("claim", "страховой случай", "File an insurance claim."),
        ("coverage", "покрытие", "Does my plan cover this?"),
        ("out-of-pocket", "из своего кармана", "Out-of-pocket maximum."),
        ("fever", "температура (высокая)", "She has a fever."),
        ("cough", "кашель", "Persistent dry cough."),
        ("sore throat", "больное горло", "Sore throat for three days."),
        ("runny nose", "насморк", "Runny nose and sneezing."),
        ("headache", "головная боль", "Migraine headache."),
        ("stomachache", "боль в животе", "Stomachache after dinner."),
        ("nausea", "тошнота", "Nausea with the medication."),
        ("dizziness", "головокружение", "Sudden dizziness."),
        ("rash", "сыпь", "Itchy rash on my arm."),
        ("swollen", "опухший", "My ankle is swollen."),
        ("bruise", "синяк", "Big bruise on my shin."),
        ("sprain", "растяжение", "Ankle sprain."),
        ("fracture", "перелом", "Hairline fracture in the wrist."),
        ("x-ray", "рентген", "X-ray showed no break."),
        ("blood test", "анализ крови", "Blood test results came in."),
        ("vaccination / shot", "прививка", "Flu shot yearly."),
        ("sick leave", "больничный", "On sick leave all week.")
    ]

    // MARK: - Животные advanced (60)
    static let animals: [Entry] = [
        ("hedgehog", "ёж", "A hedgehog in the garden."),
        ("otter", "выдра", "Otters hold hands while sleeping."),
        ("raccoon", "енот", "Raccoons raid the trash."),
        ("squirrel", "белка", "Squirrels hoard acorns."),
        ("chipmunk", "бурундук", "A chipmunk darted across."),
        ("deer", "олень", "A deer crossed the road."),
        ("moose", "лось", "Moose in the Canadian woods."),
        ("elk", "олень-вапити", "Elk bugle in the fall."),
        ("fox", "лиса", "The fox slipped into the den."),
        ("wolf", "волк", "Wolves howled at the moon."),
        ("bear", "медведь", "Brown bear on the trail."),
        ("eagle", "орёл", "Bald eagle overhead."),
        ("hawk", "ястреб", "A hawk circled the field."),
        ("owl", "сова", "Owl hooting at night."),
        ("crow", "ворона", "Crows are surprisingly smart."),
        ("raven", "ворон", "Ravens mate for life."),
        ("sparrow", "воробей", "Sparrows at the feeder."),
        ("pigeon", "голубь", "Pigeons in the square."),
        ("seagull", "чайка", "Seagulls stole my fries."),
        ("duck", "утка", "Ducks on the pond."),
        ("goose", "гусь", "Geese fly south."),
        ("swan", "лебедь", "Swans glide on the lake."),
        ("turtle", "черепаха (пресноводная)", "A turtle on the log."),
        ("tortoise", "черепаха (сухопутная)", "Tortoises live very long."),
        ("frog", "лягушка", "Frogs croak at night."),
        ("toad", "жаба", "A toad in the garden."),
        ("snake", "змея", "The snake slithered away."),
        ("lizard", "ящерица", "A lizard basking on the rock."),
        ("bat", "летучая мышь", "Bats eat mosquitoes."),
        ("rat", "крыса", "There's a rat in the basement."),
        ("mouse", "мышь", "A mouse in the kitchen."),
        ("hamster", "хомяк", "Hamster on its wheel."),
        ("rabbit", "кролик", "A rabbit hopped away."),
        ("hare", "заяц", "A hare ran across the field."),
        ("mosquito", "комар", "Mosquito bites itch."),
        ("beetle", "жук", "A shiny beetle."),
        ("ant", "муравей", "Ants in the sugar."),
        ("bee", "пчела", "Bees pollinate flowers."),
        ("wasp", "оса", "Wasp stings hurt."),
        ("butterfly", "бабочка", "Monarch butterfly migration."),
        ("moth", "мотылёк, моль", "A moth by the lamp."),
        ("spider", "паук", "A spider built a web."),
        ("worm", "червь", "Worms after the rain."),
        ("octopus", "осьминог", "An octopus in the reef."),
        ("squid", "кальмар", "Calamari is fried squid."),
        ("shrimp", "креветка", "Shrimp cocktail."),
        ("crab", "краб", "Crab cakes are popular."),
        ("lobster", "омар", "Lobster roll for lunch."),
        ("jellyfish", "медуза", "Jellyfish sting."),
        ("dolphin", "дельфин", "Dolphins follow the boat."),
        ("whale", "кит", "Whale watching tour."),
        ("shark", "акула", "A shark was spotted."),
        ("seal", "тюлень", "A seal sunbathed on the rock."),
        // parts
        ("paw", "лапа (с подушечками)", "The cat's paw."),
        ("claw", "коготь", "Sharp claws."),
        ("beak", "клюв", "A sharp beak."),
        ("fin", "плавник", "A dorsal fin."),
        ("tail", "хвост", "Wagging tail."),
        ("mane", "грива", "The lion's mane."),
        ("fur", "мех, шерсть", "Thick winter fur."),
        ("feather", "перо", "A single feather on the ground.")
    ]

    // MARK: - Одежда (35)
    static let clothing: [Entry] = [
        ("hoodie", "худи", "Put on a hoodie."),
        ("sweater", "свитер", "Wool sweater."),
        ("turtleneck", "водолазка", "Black turtleneck."),
        ("cardigan", "кардиган", "Button up the cardigan."),
        ("blazer", "пиджак, блейзер", "A navy blazer."),
        ("vest", "жилет", "Puffer vest for layering."),
        ("suit", "костюм", "Wedding suit."),
        ("tuxedo", "смокинг", "Tuxedo for the gala."),
        ("dress shirt", "рубашка (классическая)", "Iron the dress shirt."),
        ("polo shirt", "поло", "Polo shirt for work."),
        ("t-shirt", "футболка", "Plain white t-shirt."),
        ("tank top", "майка без рукавов", "Tank top for the gym."),
        ("jeans", "джинсы", "Slim-fit jeans."),
        ("shorts", "шорты", "Summer shorts."),
        ("trousers / pants", "брюки", "Dress pants."),
        ("skirt", "юбка", "A pleated skirt."),
        ("dress", "платье", "A black cocktail dress."),
        ("coat", "пальто", "Winter coat."),
        ("jacket", "куртка", "Leather jacket."),
        ("raincoat", "дождевик", "Bring a raincoat."),
        ("scarf", "шарф", "Wool scarf."),
        ("gloves", "перчатки", "Leather gloves."),
        ("hat / cap", "шапка / кепка", "Baseball cap."),
        ("beanie", "шапка-бини", "A warm beanie."),
        ("belt", "ремень", "Leather belt."),
        ("socks", "носки", "A pair of wool socks."),
        ("tights", "колготки, тайтсы", "Black tights."),
        ("sneakers", "кроссовки", "New sneakers."),
        ("loafers", "лоферы", "Brown loafers."),
        ("heels", "каблуки", "High heels hurt."),
        ("boots", "ботинки, сапоги", "Winter boots."),
        ("sandals", "сандалии", "Flip-flops or sandals."),
        // fabrics
        ("cotton", "хлопок", "100% cotton t-shirt."),
        ("wool", "шерсть", "Merino wool sweater."),
        ("silk", "шёлк", "Silk tie.")
    ]

    // MARK: - Внешность и характер (50)
    static let appearance: [Entry] = [
        ("tall", "высокий", "He's tall for his age."),
        ("short", "низкий", "She's short but athletic."),
        ("slim", "стройный", "A slim figure."),
        ("chubby", "пухлый", "A chubby toddler."),
        ("muscular", "мускулистый", "He's very muscular."),
        ("skinny", "худощавый", "Skinny jeans on a skinny guy."),
        ("curvy", "с формами", "Her curvy silhouette."),
        ("freckles", "веснушки", "Cute freckles."),
        ("dimples", "ямочки на щеках", "She has dimples when she smiles."),
        ("wrinkles", "морщины", "Wrinkles around his eyes."),
        ("tan", "загорелый", "A deep summer tan."),
        ("pale", "бледный", "Pale from winter."),
        ("bald", "лысый", "He went bald at 30."),
        ("curly hair", "кудрявые волосы", "Her curly hair."),
        ("straight hair", "прямые волосы", "Long straight hair."),
        ("wavy hair", "волнистые волосы", "Soft wavy hair."),
        ("blonde", "блондин(ка)", "Blonde highlights."),
        ("brunette", "брюнет(ка)", "She's a brunette."),
        ("redhead", "рыжий", "Natural redhead."),
        ("beard", "борода", "Full beard."),
        ("mustache", "усы", "He grew a mustache."),
        ("stubble", "щетина", "Five o'clock stubble."),
        ("piercing", "пирсинг", "Nose piercing."),
        ("tattoo", "татуировка", "A small tattoo on her wrist."),
        ("glasses", "очки", "Reading glasses."),
        // personality
        ("stubborn", "упрямый", "Stubborn as a mule."),
        ("generous", "щедрый", "She's generous with her time."),
        ("selfish", "эгоистичный", "That's a selfish decision."),
        ("kind", "добрый", "A kind neighbor."),
        ("mean", "злой, недобрый", "Don't be mean."),
        ("polite", "вежливый", "A polite young man."),
        ("rude", "грубый", "That was rude."),
        ("introvert", "интроверт", "I'm a total introvert."),
        ("extrovert", "экстраверт", "Classic extrovert."),
        ("shy", "стеснительный", "He's shy around new people."),
        ("outgoing", "общительный", "Outgoing and confident."),
        ("ambitious", "амбициозный", "She's ambitious at work."),
        ("laid-back", "расслабленный, спокойный", "He's laid-back."),
        ("down-to-earth", "приземлённый, простой", "Surprisingly down-to-earth."),
        ("confident", "уверенный", "Quietly confident."),
        ("arrogant", "высокомерный", "He comes off arrogant."),
        ("humble", "скромный", "Humble despite success."),
        ("reliable", "надёжный", "Reliable and punctual."),
        ("loyal", "преданный", "A loyal friend."),
        ("honest", "честный", "Brutally honest."),
        ("sneaky", "хитрый, скрытный", "Sneaky move."),
        ("funny", "смешной, забавный", "He's genuinely funny."),
        ("serious", "серьёзный", "Serious by nature."),
        ("curious", "любопытный", "A curious child."),
        ("creative", "творческий", "Creative problem-solver."),
        ("practical", "практичный", "Practical advice.")
    ]

    // MARK: - Инструменты и DIY (35)
    static let tools: [Entry] = [
        ("hammer", "молоток", "Hammer and nails."),
        ("screwdriver", "отвёртка", "Phillips screwdriver."),
        ("wrench", "гаечный ключ", "Adjustable wrench."),
        ("pliers", "плоскогубцы", "Needle-nose pliers."),
        ("drill", "дрель", "Cordless drill."),
        ("drill bit", "сверло", "Wood drill bit."),
        ("saw", "пила", "Hand saw."),
        ("handsaw", "ножовка", "Use a handsaw."),
        ("chainsaw", "бензопила", "Chainsaw for logs."),
        ("tape measure", "рулетка (измерительная)", "Grab the tape measure."),
        ("level", "уровень", "Use a spirit level."),
        ("sandpaper", "наждачная бумага", "Fine-grit sandpaper."),
        ("paintbrush", "кисть", "Clean the paintbrush."),
        ("roller", "валик", "Paint roller."),
        ("caulk", "герметик", "Apply caulk around the tub."),
        ("duct tape", "клейкая лента, скотч", "Duct tape fixes everything."),
        ("electrical tape", "изолента", "Black electrical tape."),
        ("nail", "гвоздь", "A box of nails."),
        ("screw", "винт, шуруп", "Machine screws."),
        ("bolt", "болт", "Tighten the bolt."),
        ("nut", "гайка", "Don't lose the nut."),
        ("washer", "шайба", "Add a washer."),
        ("anchor", "дюбель", "Wall anchor for drywall."),
        ("bracket", "кронштейн", "Shelf bracket."),
        ("stud finder", "детектор балок (в стене)", "Use a stud finder."),
        ("ladder", "лестница (приставная)", "Climb the ladder carefully."),
        ("step stool", "стремянка (маленькая)", "Grab the step stool."),
        ("toolbox", "ящик для инструментов", "Everything in the toolbox."),
        ("workbench", "верстак", "Sturdy workbench."),
        ("vise", "тиски", "Clamp it in the vise."),
        ("clamp", "струбцина", "C-clamp for gluing."),
        ("extension cord", "удлинитель", "Heavy-duty extension cord."),
        ("power strip", "сетевой фильтр", "Surge-protected power strip."),
        ("flashlight", "фонарик", "Emergency flashlight."),
        ("safety goggles", "защитные очки", "Wear safety goggles.")
    ]

    // MARK: - Цвета (оттенки) (30)
    static let colors: [Entry] = [
        ("teal", "бирюзовый (тёмный)", "Teal walls in the bathroom."),
        ("turquoise", "бирюзовый (ярче)", "Turquoise ocean water."),
        ("navy", "тёмно-синий", "Navy suit."),
        ("sky blue", "небесно-голубой", "Sky blue shirt."),
        ("baby blue", "нежно-голубой", "Baby blue blanket."),
        ("beige", "бежевый", "Beige carpet."),
        ("cream", "кремовый", "Cream-colored walls."),
        ("ivory", "слоновой кости", "Ivory keys."),
        ("taupe", "серо-коричневый", "Taupe curtains."),
        ("charcoal", "антрацитовый, тёмно-серый", "Charcoal gray suit."),
        ("slate gray", "шифер, тёмно-сизый", "Slate gray tiles."),
        ("maroon", "бордовый", "A maroon scarf."),
        ("burgundy", "бургундский, тёмно-красный", "Burgundy wine."),
        ("crimson", "малиновый, кроваво-красный", "Crimson banner."),
        ("coral", "коралловый", "Coral lipstick."),
        ("peach", "персиковый", "Peach sunset."),
        ("salmon", "лососевый", "Salmon pink walls."),
        ("mustard", "горчичный", "Mustard yellow sweater."),
        ("olive", "оливковый", "Olive green jacket."),
        ("mint", "мятный", "Mint green fridge."),
        ("sage", "шалфейно-зелёный", "Sage walls."),
        ("forest green", "тёмно-зелёный (лесной)", "Forest green hoodie."),
        ("lavender", "лавандовый", "Lavender pillowcase."),
        ("lilac", "сиреневый", "Lilac blooms."),
        ("magenta", "пурпурный", "Magenta highlight."),
        ("plum", "сливовый", "Plum eyeshadow."),
        ("rust", "ржавый", "Rust-colored jacket."),
        ("caramel", "карамельный", "Caramel highlights."),
        ("bronze", "бронзовый", "Bronze medal."),
        ("copper", "медный", "Copper pots.")
    ]

    // MARK: - Авто (35)
    static let cars: [Entry] = [
        ("car", "автомобиль", "Parking the car."),
        ("truck", "грузовик, пикап", "Pickup truck."),
        ("SUV", "кроссовер, внедорожник", "Family SUV."),
        ("sedan", "седан", "Four-door sedan."),
        ("hatchback", "хэтчбек", "Compact hatchback."),
        ("minivan", "минивэн", "Minivan for the kids."),
        ("steering wheel", "руль", "Hands on the steering wheel."),
        ("dashboard", "приборная панель", "Warning light on the dashboard."),
        ("glove compartment", "бардачок", "Registration in the glove compartment."),
        ("gear (shift)", "рычаг КПП", "Shift into gear."),
        ("clutch", "сцепление", "Clutch pedal (manual)."),
        ("brake", "тормоз", "Hit the brake."),
        ("accelerator / gas pedal", "педаль газа", "Ease off the accelerator."),
        ("handbrake", "ручник", "Release the handbrake."),
        ("ignition", "зажигание", "Turn the ignition."),
        ("battery", "аккумулятор", "Dead battery."),
        ("engine", "двигатель", "Engine won't start."),
        ("hood", "капот", "Check under the hood."),
        ("trunk", "багажник", "Load the trunk."),
        ("bumper", "бампер", "Cracked front bumper."),
        ("fender", "крыло (кузова)", "Dented fender."),
        ("headlight", "фара", "High beams / low beams."),
        ("taillight", "задний фонарь", "Broken taillight."),
        ("turn signal / indicator", "поворотник", "Use your turn signal."),
        ("windshield", "лобовое стекло", "Chip in the windshield."),
        ("windshield wiper", "дворник", "Windshield wipers stopped."),
        ("rearview mirror", "зеркало заднего вида", "Adjust the rearview mirror."),
        ("side mirror", "боковое зеркало", "Clipped the side mirror."),
        ("tire", "шина", "Flat tire."),
        ("spare tire", "запаска", "Spare tire in the trunk."),
        ("wheel", "колесо", "Alloy wheels."),
        ("fuel / gas", "топливо / бензин", "Out of gas."),
        ("diesel", "дизель", "Diesel engine."),
        ("gas station", "заправка", "Stop at the gas station."),
        ("registration", "регистрация (машины)", "Expired registration.")
    ]

    // MARK: - Спорт / фитнес (40)
    static let sports: [Entry] = [
        ("soccer / football", "футбол (европейский)", "Soccer match."),
        ("American football", "американский футбол", "Superbowl is American football."),
        ("basketball", "баскетбол", "Basketball court."),
        ("baseball", "бейсбол", "Baseball season."),
        ("tennis", "теннис", "Tennis court."),
        ("volleyball", "волейбол", "Beach volleyball."),
        ("hockey", "хоккей", "Ice hockey."),
        ("golf", "гольф", "Play a round of golf."),
        ("swimming", "плавание", "Swimming laps."),
        ("running", "бег", "Morning running."),
        ("cycling", "велоспорт", "Cycling on weekends."),
        ("skiing", "лыжный спорт", "Downhill skiing."),
        ("snowboarding", "сноуборд", "Snowboarding in Hokkaido."),
        ("surfing", "сёрфинг", "Surfing the waves."),
        ("climbing", "скалолазание", "Rock climbing."),
        ("hiking", "пеший туризм", "Hiking the trail."),
        ("boxing", "бокс", "Boxing gym."),
        ("MMA", "смешанные единоборства", "UFC is MMA."),
        ("wrestling", "борьба", "Greco-Roman wrestling."),
        ("yoga", "йога", "Yoga class."),
        ("pilates", "пилатес", "Pilates reformer."),
        ("CrossFit", "кроссфит", "CrossFit workout."),
        ("team", "команда", "Team captain."),
        ("coach", "тренер", "Great coach."),
        ("referee", "рефери, судья", "The referee blew the whistle."),
        ("score", "счёт", "Final score 3-1."),
        ("goal", "гол", "He scored a goal."),
        ("match / game", "матч / игра", "Watch the match."),
        ("tournament", "турнир", "Weekend tournament."),
        ("championship", "чемпионат", "World championship."),
        ("league", "лига", "Premier League."),
        ("practice", "тренировка (спорт)", "Practice three times a week."),
        ("training", "тренировочный процесс", "Training camp."),
        ("warm up", "разогреваться", "Warm up before the game."),
        ("stretch", "растянуться", "Stretch after running."),
        ("injury", "травма", "Knee injury."),
        ("recovery", "восстановление", "Rest for recovery."),
        ("fitness", "физическая форма", "Cardio fitness."),
        ("stamina", "выносливость", "Build stamina."),
        ("champion", "чемпион", "Olympic champion.")
    ]
}
